# Generated by Django 2.1.7 on 2019-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名稱')),
                ('price', models.PositiveSmallIntegerField(verbose_name='商品價格')),
                ('place', models.CharField(max_length=255, verbose_name='商品所在地點')),
                ('specification', models.CharField(max_length=255, verbose_name='商品規格')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
