# Generated by Django 2.2 on 2019-04-17 08:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
