# Generated by Django 2.2 on 2019-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190417_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='class_s',
            field=models.IntegerField(choices=[(0, '3C'), (1, '生活'), (2, '通訊'), (3, '日用'), (4, '周邊'), (5, '食品'), (6, 'N B'), (7, '戶外'), (8, '數位'), (9, '時尚'), (10, '家電'), (11, '美妝')], null=True, verbose_name='分類'),
        ),
    ]
